spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tongxingmao?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: tong
    password: tong
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8086

logging:
  level:
    org.springframework: error
